[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "e817d9da002a58166725401f8cd2b11e699b171f"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "ea51fc7a6bd9196a46e6d6d09d78971c472d5552837fb357bedd3b7aeecab335"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.5%2B0/iceberg_rust_ffi.v0.2.5.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "c5f6516a6c16961b0a22dd40f96fbc5d84e798e6"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "0b6c7bcba407ea40e27e8c01f3a097d5aff73cadc5356a139cf0287cbbf22f40"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.5%2B0/iceberg_rust_ffi.v0.2.5.x86_64-linux-gnu.tar.gz"
