[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "d93f9c20caae16840f0f088e3d2aacd479ee754b"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "3b68eda44a53a52941a3f52809c704c4593a3b9f612920a733b9f2eb9990fcca"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.2%2B0/iceberg_rust_ffi.v0.2.2.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "a6ac72131b708a75304f27de279b4d86f103a279"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "6bc43a821830d29b82d25b694812f36eefb1c93cdf25505ca915219a6160d3a2"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.2%2B0/iceberg_rust_ffi.v0.2.2.x86_64-linux-gnu.tar.gz"
