[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "4e3b8b5c238709572b1900c5289805537d5f78bf"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "348338b4d7a241f0e371495e535eaecabcf09c8a4e6b1b9cb406ea9d88206728"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.7%2B0/iceberg_rust_ffi.v0.2.7.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "29a34460e6a3e3f0e1aff0daadff414fb5bd9f19"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "1eba3823411bc71f2e066d638a939337cc77a90e86409c9a8b89e5fd17655274"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.7%2B0/iceberg_rust_ffi.v0.2.7.x86_64-linux-gnu.tar.gz"
