[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "f7d8bc56eed1b24551303d3d5daaa1b8ca1df7b4"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "4eac0477e77da5479af3573ee3379fe6f7767285587354282b393fca1b231500"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.5%2B0/iceberg_rust_ffi.v0.5.5.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "d15ba6e4bac490ee71ab0c889a6a9b31838bf5ce"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "e36989d7f35463ca3de194d8d85d535dd743f69fc0f3d3c798c59a465bfb2e4e"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.5%2B0/iceberg_rust_ffi.v0.5.5.x86_64-linux-gnu.tar.gz"
