[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "293ee53452f92f36e5b66007550a97779617897c"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "f8e6d03e6484026d4d22959fa0bad0754be9eea14cd632088a11b17844cf25b8"
    url = "file:///home/runner/work/iceberg_rust_ffi_jll.jl/iceberg_rust_ffi_jll.jl/products/iceberg_rust_ffi.v0.1.6.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "943cadefa5e9392559a40fcc80bb981d92e5d19c"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "9576ed79316a5b96f8fd8096786e9734a043bad73c8b863303c0449c89adc49b"
    url = "file:///home/runner/work/iceberg_rust_ffi_jll.jl/iceberg_rust_ffi_jll.jl/products/iceberg_rust_ffi.v0.1.6.x86_64-linux-gnu.tar.gz"
