[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "5ce3f974325cae3d9540cc5ece8b1e5c32765e77"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "bc255f74e8f66f26a31d0a3e671fc66b098f9c4357ca4e7fe3c4073c2ecd2554"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.2%2B0/iceberg_rust_ffi.v0.5.2.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "df31424966d682e5cdf2db0599b953a3c87a9c8a"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "874f32b129739ffa8751eaa95468d56fdb132de98aa73511229d6ed6f3df98fa"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.5.2%2B0/iceberg_rust_ffi.v0.5.2.x86_64-linux-gnu.tar.gz"
