[[iceberg_rust_ffi]]
arch = "aarch64"
git-tree-sha1 = "591ddb4ba7ce3795878c1efeadcb1a7b8fd550bb"
os = "macos"

    [[iceberg_rust_ffi.download]]
    sha256 = "b8703d87a4b711f40d6d107d1869d7c2683b020aaefb6c984cb038f7f8df2a3c"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.4%2B0/iceberg_rust_ffi.v0.2.4.aarch64-apple-darwin.tar.gz"
[[iceberg_rust_ffi]]
arch = "x86_64"
git-tree-sha1 = "0971210ac16079f10143aeb63c15f28a64fe90d9"
libc = "glibc"
os = "linux"

    [[iceberg_rust_ffi.download]]
    sha256 = "b6262b8172ffaf041163ca25d703152ec648c4c3efc7a4e1c7efe3c8abbad1ce"
    url = "https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v0.2.4%2B0/iceberg_rust_ffi.v0.2.4.x86_64-linux-gnu.tar.gz"
