name = "iceberg_rust_ffi_binarybuilder"
uuid = "e0000791-2b28-4943-8eb7-81f8447c0023"
authors = ["Vukasin Stefanovic <vukasin.stefanovic92@gmail.com>"]
version = "0.1.0"

[deps]
BinaryBuilder = "12aac903-9f7c-5d81-afc2-d9565ea332ae"
