# Autogenerated wrapper script for iceberg_rust_ffi_jll for aarch64-apple-darwin
export libiceberg_rust_ffi

JLLWrappers.@generate_wrapper_header("iceberg_rust_ffi")
JLLWrappers.@declare_library_product(libiceberg_rust_ffi, "@rpath/libiceberg_rust_ffi.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libiceberg_rust_ffi,
        "lib/libiceberg_rust_ffi.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
