# Autogenerated wrapper script for iceberg_rust_ffi_jll for x86_64-linux-gnu
export libiceberg_rust_ffi

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("iceberg_rust_ffi")
JLLWrappers.@declare_library_product(libiceberg_rust_ffi, "libiceberg_rust_ffi.so")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        libiceberg_rust_ffi,
        "lib/libiceberg_rust_ffi.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
