name: Build and Deploy Tarballs

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Name for the new branch to create (must not exist)'
        required: true
        type: string
      base_version:
        description: 'Base version to use (e.g., "0.1.0")'
        required: true
        type: string
      commit_sha:
        description: 'Commit SHA to use for the build (e.g., "abc123...")'
        required: true
        type: string
      targets:
        description: 'Target platforms to build for (comma-separated)'
        required: false
        default: 'x86_64-linux-gnu,aarch64-apple-darwin'
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Print workflow inputs
      run: |
        echo "=== Workflow Inputs ==="
        echo "Branch name: ${{ github.event.inputs.branch_name }}"
        echo "Base version: ${{ github.event.inputs.base_version }}"
        echo "Commit SHA: ${{ github.event.inputs.commit_sha }}"
        echo "Targets: ${{ github.event.inputs.targets }}"
        echo "======================"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate branch name
      run: |
        branch_name="${{ github.event.inputs.branch_name }}"
        if [ "$branch_name" = "main" ]; then
          echo "Error: Cannot create a branch named 'main'."
          exit 1
        fi

        # Check if branch already exists
        if git ls-remote --heads origin "$branch_name" | grep -q "$branch_name"; then
          echo "Error: Branch '$branch_name' already exists. Please choose a different branch name."
          exit 1
        fi

        echo "Branch name validation passed: $branch_name"

    - name: Create and checkout new branch
      run: |
        branch_name="${{ github.event.inputs.branch_name }}"
        git checkout -b "$branch_name"
        echo "Created and checked out branch: $branch_name"

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.7.3'

    - name: Install dependencies
      run: |
        julia --project=iceberg_rust_ffi_binarybuilder -e 'using Pkg; Pkg.instantiate()'

    - name: Update build_tarballs.jl with new version and commit SHA
      run: |
        branch_name="${{ github.event.inputs.branch_name }}"
        base_version="${{ github.event.inputs.base_version }}"
        commit_sha="${{ github.event.inputs.commit_sha }}"
        new_version="${base_version}"

        echo "Using provided commit SHA: $commit_sha"

        echo "Updating build_tarballs.jl with version: $new_version and commit SHA: $commit_sha"

        # Update the version line in build_tarballs.jl
        sed -i "s/version = v\"[^\"]*\"/version = v\"$new_version\"/" iceberg_rust_ffi_binarybuilder/build_tarballs.jl

        # Update the GitSource commit SHA in build_tarballs.jl
        sed -i "s/GitSource(\"https:\/\/github.com\/RelationalAI\/iceberg_rust_ffi.git\", \"[a-f0-9]*\")/GitSource(\"https:\/\/github.com\/RelationalAI\/iceberg_rust_ffi.git\", \"$commit_sha\")/" iceberg_rust_ffi_binarybuilder/build_tarballs.jl

        echo "Updated build_tarballs.jl:"
        echo "Version:"
        grep "version = v" iceberg_rust_ffi_binarybuilder/build_tarballs.jl
        echo "GitSource:"
        grep "GitSource" iceberg_rust_ffi_binarybuilder/build_tarballs.jl

    - name: Show full build_tarballs.jl contents
      run: |
        echo "Full contents of build_tarballs.jl:"
        cat iceberg_rust_ffi_binarybuilder/build_tarballs.jl

    - name: Build tarballs
      run: |
        echo "Building tarballs with updated version"
        julia --project=iceberg_rust_ffi_binarybuilder iceberg_rust_ffi_binarybuilder/build_tarballs.jl --verbose --deploy-bin="RelationalAI/iceberg_rust_ffi_jll.jl" ${{ github.event.inputs.targets }}
      env:
        BINARYBUILDER_AUTOMATIC_APPLE: true
        BINARYBUILDER_RUNNER: true

    - name: Update Project.toml and Artifacts.toml with new version and release URLs
      run: |
        # Get the version from the build_tarballs.jl file
        version=$(grep 'version = v"' iceberg_rust_ffi_binarybuilder/build_tarballs.jl | sed 's/.*version = v"\([^"]*\)".*/\1/')
        echo "Detected version: $version"
        
        # Update Project.toml with new version
        new_project_version="${version}+0"
        echo "Updating Project.toml with version: $new_project_version"
        sed -i "s/version = \"[^\"]*\"/version = \"$new_project_version\"/" Project.toml
        echo "Updated Project.toml version:"
        grep "version =" Project.toml

        echo "Building JLL"
        julia --project=iceberg_rust_ffi_binarybuilder iceberg_rust_ffi_binarybuilder/build_tarballs.jl --verbose --deploy-jll="local" ${{ github.event.inputs.targets }} --skip-build

        cp ~/.julia/dev/iceberg_rust_ffi_jll/Artifacts.toml Artifacts.toml

        targets="${{ github.event.inputs.targets }}"

        # Check if x86_64-linux-gnu is in targets and apply sed if it is
        if echo "$targets" | grep -q "x86_64-linux-gnu"; then
          echo "x86_64-linux-gnu found in targets, updating Artifacts.toml"
          X86_64_URL="https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v${version}%2B0/iceberg_rust_ffi.v${version}.x86_64-linux-gnu.tar.gz"
          sed -i.tmp \
              -e "/x86_64-linux-gnu.tar.gz/s|url = \".*\"|url = \"$X86_64_URL\"|" \
              "Artifacts.toml"
        else
          echo "x86_64-linux-gnu not in targets, skipping Artifacts.toml update for this platform"
        fi

        # Check if aarch64-apple-darwin is in targets and apply sed if it is
        if echo "$targets" | grep -q "aarch64-apple-darwin"; then
          echo "aarch64-apple-darwin found in targets, updating Artifacts.toml"
          AARCH64_URL="https://github.com/RelationalAI/iceberg_rust_ffi_jll.jl/releases/download/iceberg_rust_ffi-v${version}%2B0/iceberg_rust_ffi.v${version}.aarch64-apple-darwin.tar.gz"
          sed -i.tmp \
              -e "/aarch64-apple-darwin.tar.gz/s|url = \".*\"|url = \"$AARCH64_URL\"|" \
              "Artifacts.toml"
        else
          echo "aarch64-apple-darwin not in targets, skipping Artifacts.toml update for this platform"
        fi

        # Verify the update was successful
        echo "Updated Artifacts.toml contents:"
        cat Artifacts.toml

        echo "Successfully updated Artifacts.toml with version $version"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Artifacts.toml Project.toml iceberg_rust_ffi_binarybuilder/build_tarballs.jl
        git commit -m "Update build_tarballs.jl version, Project.toml version, and Artifacts.toml with new tarball URLs"
        git push origin ${{ github.event.inputs.branch_name }}