name: Build and Deploy Tarballs

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Branch to build and deploy from'
        required: true
        default: 'main'
        type: string
      targets:
        description: 'Target platforms to build for (comma-separated)'
        required: false
        default: 'x86_64-linux-gnu'
        type: string
      version:
        description: 'Version to build (optional, will use current version if not specified)'
        required: false
        type: string

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - name: Validate target branch
      run: |
        if [ "${{ github.event.inputs.target_branch }}" = "main" ]; then
          echo "Error: Deployment to main branch is not allowed for safety reasons."
          echo "Please use a different branch for deployment."
          exit 1
        fi
        echo "Target branch validation passed: ${{ github.event.inputs.target_branch }}"

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.target_branch }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.7.3'

    - name: Install dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Show current version
      run: |
        julia --project=. -e 'using Pkg; println("Current version: ", Pkg.project().version)'

    - name: Build tarballs
      run: |
        if [ -n "${{ github.event.inputs.version }}" ]; then
          echo "Building for version: ${{ github.event.inputs.version }}"
          julia --project=. build_tarballs.jl --verbose --deploy-bin="RelationalAI/iceberg_rust_ffi_jll" --targets ${{ github.event.inputs.targets }} --version ${{ github.event.inputs.version }}
        else
          echo "Building for current version"
          julia --project=. build_tarballs.jl --verbose --deploy-bin="RelationalAI/iceberg_rust_ffi_jll" --targets ${{ github.event.inputs.targets }}
        fi
      env:
        BINARYBUILDER_AUTOMATIC_APPLE: true
        BINARYBUILDER_RUNNER: true

    - name: Update Artifacts.toml
      run: |
        julia --project=. -e '
        using Pkg
        Pkg.add("BinaryBuilder")
        using BinaryBuilder
        BinaryBuilder.update_Artifacts_toml("Artifacts.toml")
        '

    - name: Show updated Artifacts.toml
      run: |
        echo "Updated Artifacts.toml contents:"
        cat Artifacts.toml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Artifacts.toml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Artifacts.toml with new tarball URLs"
          git push origin ${{ github.event.inputs.target_branch }}
        fi 